runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: templates/blog.html
  upload: templates/blog.html

- url: /css
  static_dir: templates/css

- url: /js
  static_dir: templates/js

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

libraries:
- name: jinja2
  version: latest
